'use strict';
let state=null, model='all', paused=false, lastMessage=0, selected=null;
const $=id=>document.getElementById(id);
const number=value=>value==null?'—':new Intl.NumberFormat('en-US').format(value);
const shortModel=name=>name?.includes('luna')?'Luna':name?.includes('sol')?'Sol':name?.includes('astra')?'Astra':name||'Unknown';
const fits=name=>model==='all'||(name||'').includes(model);
function element(tag,text,cls){const e=document.createElement(tag);if(text!=null)e.textContent=text;if(cls)e.className=cls;return e;}
function time(value){return value?new Date(value*1000).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit',second:'2-digit'}):'—';}
function saving(value,label){const box=element('div',null,'saving '+(value==null?'unknown':value>=0?'good':'bad'));box.append(element('small',label));box.append(element('strong',value==null?'—':`${value.toFixed(1)}%`));return box;}
function renderFocus(runs){if(!runs.some(r=>r.id===selected))selected=runs.find(r=>r.arm==='on')?.id||runs[0]?.id;const menu=$('focus-run');menu.replaceChildren(...runs.map(r=>{const option=element('option',`${shortModel(r.model)} · ${r.experiment} · ${r.arm==='on'?'Helix':'control'}`);option.value=r.id;option.selected=r.id===selected;return option;}));const current=runs.find(r=>r.id===selected);if(!current)return;const pair=state.pairs.find(p=>p.id===current.experiment_id),off=state.runs.find(r=>r.id===pair.off),on=state.runs.find(r=>r.id===pair.on);
 $('focus-title').textContent=`${shortModel(current.model)} High · ${current.experiment} · ${current.arm==='on'?'Helix candidate':'Control'}`;$('phase').textContent=`Observed phase: ${current.phase||'Unclassified'} · ${current.state} · receipt ${current.source_hash?.slice(0,12)||'unavailable'}`;
 const fields=[['Native input',r=>r?.usage?.input_tokens],['Native output',r=>r?.usage?.output_tokens],['Reported reasoning output',r=>r?.usage?.reasoning_output_tokens],['Raw source bytes',r=>r?.raw_source_bytes],['Model-visible bytes',r=>r?.model_visible_bytes],['Recorded tool bytes',r=>r?.recorded_tool_bytes],['Tool calls (commands)',r=>r?.commands],['Engine calls',r=>r?.engine_calls],['Engine operations',r=>r?.engine_operations],['Suspected Engine-read output bytes',r=>r?.suspected_engine_read_output_bytes],['Generated command bytes',r=>r?.generated_command_bytes],['Glue / setup tokens',()=>null]];
 $('comparison').replaceChildren();for(const [label,get] of fields){const a=get(off),b=get(on),change=a!=null&&a>0&&b!=null?(b/a-1)*100:null;const tr=element('tr');tr.append(element('td',label),element('td',number(a)),element('td',number(b)),element('td',change==null?'—':`${change>0?'+':''}${change.toFixed(1)}%`,change==null?'muted':change<=0?'good':'bad'));$('comparison').append(tr);}const checked=r=>r?.artifact_check===true?'PASS':r?.artifact_check===false?'FAIL':'UNVERIFIED';const tr=element('tr');tr.append(element('td','Artifact checks'),element('td',checked(off)),element('td',checked(on)),element('td','Parity unproven','unknown'));$('comparison').append(tr);
 $('delegated').textContent=current.delegated_work;$('engine-time').textContent=current.engine_seconds==null?'Unmeasured':(current.engine_seconds*1000).toFixed(3)+' ms';$('mechanisms').textContent=Object.entries(current.mechanisms||{}).map(([k,v])=>`${k}: ${v}`).join(' · ');
 $('timeline').replaceChildren(...(current.timeline||[]).map(event=>{const li=element('li');const stamp=event.execution_timestamp==null?'—':String(event.execution_timestamp);li.append(element('span',stamp,'event-time'),element('span','#'+event.sequence,'event-seq'),element('span',event.type+' '+event.detail),element('span',event.recorded_output_bytes==null?'':number(event.recorded_output_bytes)+' B recorded','event-value'));if(event.exit_code!=null)li.append(element('span','exit '+event.exit_code,event.exit_code===0?'good':'bad'));return li;}));$('timeline-note').textContent='Source order · observed '+time(state.observed_at)+' · missing execution timestamps shown as —';
}
function render(){if(!state||paused)return;const runs=state.runs.filter(r=>fits(r.model)), pairs=state.pairs.filter(p=>fits(p.model));
 $('scope').textContent=state.scope;renderFocus(runs);
 $('active').textContent=runs.filter(r=>r.state==='RUNNING').length;
 $('active-note').textContent=`${runs.filter(r=>['STALE','RUNNING_UNVERIFIED'].includes(r.state)).length} stale / unverified process reports`;
 for(const [id,key] of [['input','input_tokens'],['output','output_tokens']]){const known=runs.filter(r=>r.usage?.[key]!=null);$(id).textContent=known.length?number(known.reduce((n,r)=>n+r.usage[key],0)):'—';}
 $('gaps').textContent=runs.filter(r=>r.usage?.input_tokens==null||r.usage?.output_tokens==null).length+' runs unmetered';
 $('count').textContent=pairs.length+' comparisons';$('scan').textContent=time(state.observer?.last_scan);$('revision').textContent='REV '+state.revision;
 $('updated').textContent='Snapshot '+time(state.observed_at);$('pairs').replaceChildren();
 for(const p of pairs){const card=element('article',null,'pair');const title=element('div');title.append(element('h3',p.name),element('div',shortModel(p.model)+' High · '+p.classification,'meta'),element('div',p.artifact_check===true?'ARTIFACT CHECKS PASSED · PARITY UNPROVEN':p.artifact_check===false?'ARTIFACT CHECK FAILED':'ARTIFACT CHECKS UNVERIFIED','check'));card.append(title,saving(p.savings.input_tokens,'INPUT SAVED'),saving(p.savings.output_tokens,'OUTPUT SAVED'));$('pairs').append(card);}
 if(!pairs.length)$('pairs').append(element('p','No registered comparisons for this model.','empty'));
 $('runs').replaceChildren();for(const r of runs){const tr=element('tr');const values=[r.experiment+' / '+(r.arm==='off'?'control':'Helix'),shortModel(r.model),r.state,number(r.usage?.input_tokens),number(r.usage?.output_tokens),typeof r.elapsed_seconds==='number'?r.elapsed_seconds.toFixed(1)+'s':'—',r.last_event||'—'];values.forEach((v,i)=>tr.append(element('td',v,i===2?'state '+(r.state==='COMPLETED'?'good':r.state==='RUNNING'?'unknown':'bad'):null)));const td=element('td');const link=element('a','Receipt ↗');link.href='/api/receipt?id='+encodeURIComponent(r.id);link.target='_blank';link.rel='noopener';td.append(link);tr.append(td);$('runs').append(tr);}
 const alerts=[];if(state.observer?.error)alerts.push('Observer error: '+state.observer.error+'. Last snapshot may be stale.');for(const p of state.problems||[])if(runs.some(r=>r.id===p.run))alerts.push(p.message);for(const p of pairs)if(Object.values(p.savings).some(v=>v!=null&&v<0))alerts.push(shortModel(p.model)+' · '+p.name+' has a token regression.');if(runs.some(r=>r.state==='STALE'))alerts.push('A reported running process is no longer identifiable.');if(!alerts.length)alerts.push('No measured regression in this view. General parity remains unproven.');$('alerts').replaceChildren(...alerts.map(t=>element('li',t)));
}
for(const button of document.querySelectorAll('[data-model]'))button.addEventListener('click',()=>{model=button.dataset.model;for(const b of document.querySelectorAll('[data-model]')){b.classList.toggle('active',b===button);b.setAttribute('aria-pressed',String(b===button));}render();});
$('pause').addEventListener('click',()=>{paused=!paused;$('pause').textContent=paused?'Resume view':'Pause view';$('pause').setAttribute('aria-pressed',String(paused));if(!paused)render();updateConnection();});
function updateConnection(){const fresh=Date.now()-lastMessage<12000;const error=state?.observer?.error;const text=paused?'VIEW PAUSED':error?'OBSERVER ERROR':fresh?'LIVE · FILE OBSERVER':'DISCONNECTED';$('connection').textContent=text;$('light').style.background=fresh&&!error&&!paused?'var(--accent)':'var(--amber)';$('clock').textContent=new Date().toLocaleTimeString();}
const stream=new EventSource('/api/events');stream.onmessage=e=>{try{state=JSON.parse(e.data);lastMessage=Date.now();render();updateConnection();}catch(error){$('connection').textContent='INVALID TELEMETRY';}};stream.onerror=()=>{lastMessage=0;updateConnection();};setInterval(updateConnection,1000);
$('focus-run').addEventListener('change',()=>{selected=$('focus-run').value;if(!paused)render();});
