export type Detail = { title: string; eyebrow: string; summary: string; sections: { title: string; text: string }[] };
export const models = [
  { name: 'Sol', symbol: 'sun', input: 67.3, output: 71.9, status: 'Strongest result', tone: 'green', method: 'Caller-side deterministic completion', note: 'Semantic judgment in. Exact assembly out.', detail: { title: 'Sol High', eyebrow: 'REPORTED OBSERVATION · NOT INDEPENDENTLY VERIFIED', summary: 'The strongest supplied end-to-end result: 67.3% less native input and 71.9% less native output, with correct artifacts reported for both arms.', sections: [ { title: 'What changed', text: 'Sol makes the semantic selection. The caller assembles the exact artifact and verifies its bytes, rather than asking Sol to emit the mechanical completion. Historical selective evidence achieved 49.6% input and 50.0% output savings on its own.' }, { title: 'The remaining distance', text: 'Relative to the original baseline, 75/75 requires another 7.7 input points and 3.1 output points. That is 23.5% of remaining input and 11.0% of remaining output. Reaching 80/80 requires 12.7 and 8.1 points: 38.8% and 28.8% of the residuals.' }, { title: 'Do not multiply the savings', text: 'Evidence selection and caller completion may remove the same source copying, history, and procedural work. The tempting 83.5/86.0 estimate assumes independent residual effects that have not been demonstrated. Cross-experiment percentages do not identify causal overlap.' }, { title: 'Assessment', text: '75/75 is a plausible task-family hypothesis for assembly-heavy work, not an established result. 80/80 needs a sufficiently small fixed-plus-semantic floor and little reconstruction. Novel reasoning-heavy tasks may have no such removable fraction.' } ] } },
  { name: 'Luna', symbol: 'moon', input: -62.4, output: -43.9, status: 'Overhead risk', tone: 'amber', method: 'Cold generic named-plan experiment', note: 'Abstraction overhead outweighs local savings.', detail: { title: 'Luna High', eyebrow: 'REPORTED OBSERVATION · NOT INDEPENDENTLY VERIFIED', summary: 'The cold generic named-plan experiment used 62.4% more input and 43.9% more output despite a correct final artifact.', sections: [ { title: 'Observed behavior', text: 'The supplied report describes substantial Engine source inspection, integration/setup code generation, and extra verification. A separate selective-memory experiment reduced input by 39.7% but increased output by about 15%.' }, { title: 'Working hypothesis', text: 'An unfamiliar abstraction may be interpreted as an integration task. This is a behavioral hypothesis, not access to hidden reasoning. Smaller evidence packets can trigger larger orchestration and reconstruction costs.' }, { title: 'Minimal phenotype', text: 'Expose a tiny, stable, typed command surface with explicit preconditions, examples, exact error semantics, and a native fallback. Do not require generic API discovery or helper-source inspection. Preserve the ability to inspect exact evidence and bypass the Engine when needed.' }, { title: 'Strategic role', text: 'Prioritize native bypass and negative-cost detection before adding capabilities. If Sol reaches 75% cost savings at equal quality, compare actual price-weighted task costs before spending further research effort on Luna. No price dominance is established by token percentages alone.' } ] } },
  { name: 'Astra', symbol: 'sparkles', input: 25.7, output: 38.6, status: 'High-value target', tone: 'purple', method: 'Historical exact-evidence experiment', note: 'Preserve caution. Outsource mechanical checks.', detail: { title: 'Astra High', eyebrow: 'REPORTED OBSERVATION + ARCHITECTURAL HYPOTHESIS', summary: 'Historical exact evidence reportedly saved 25.7% of input and 38.6% of output. Strong caller-side completion results are not yet established.', sections: [ { title: 'What is not known', text: 'Repeated verification, source inspection, and state reconstruction are suspected cost centers. They are not direct observations of hidden reasoning. Attribute costs using visible tool calls, emitted artifacts, and provider usage—not invented reasoning categories.' }, { title: 'Smallest proposed receipt', text: 'Expose a versioned operation ID, input root, executor and verifier versions, output root, exit status, checked predicates, unchecked obligations, and exact-evidence retrieval handle. Attach a checker verdict from a configured trusted boundary. Do not ask the model to validate a long cryptographic proof in tokens.' }, { title: 'Integrity is not correctness', text: 'A hash binds bytes; it does not prove that the bytes are correct. A signature identifies an issuer; it does not prove the issuer’s assertions. A test receipt proves only that the stated tests ran with the recorded result. The checker, policies, and environment remain explicit trust assumptions.' }, { title: 'Retain genuine caution', text: 'Astra still judges requirement adequacy, evidence sufficiency, unexpected effects, and semantic correctness. Stale dependencies, an unrecognized verifier, failed predicates, or missing evidence trigger retrieval or native verification—not automatic acceptance.' } ] } },
];
export const sources = [
 { id: 'S01', title: 'MemGPT: Towards LLMs as Operating Systems', author: 'Packer et al. · Research paper', area: 'Memory systems', url: 'https://arxiv.org/abs/2310.08560', finding: 'Virtual context management and explicit movement between memory tiers. An architectural precedent, not evidence of native token savings for Helix.' },
 { id: 'S02', title: 'Remote caching', author: 'Bazel · Official documentation', area: 'Incremental computation', url: 'https://bazel.build/remote/caching', finding: 'Action hashes map to result metadata; content-addressed output storage supports verified reuse. Declared inputs, environment, and toolchain identity are essential for correct invalidation.' },
 { id: 'S03', title: 'PREPARE', author: 'PostgreSQL · Official documentation', area: 'Database systems', url: 'https://www.postgresql.org/docs/current/sql-prepare.html', finding: 'Separate parse/analyze work from execution. Generic and parameter-specific plans trade reuse against specialization. Dependency changes may force replanning.' },
 { id: 'S04', title: 'Proof-Carrying Code', author: 'George C. Necula · POPL 1997 / author bibliography', area: 'Verification', url: 'https://people.eecs.berkeley.edu/~necula/papers.html', finding: 'A foundational precedent for mechanically checked properties attached to code. A Helix execution receipt is not automatically a formal proof-carrying-code system.' },
 { id: 'S05', title: 'RTK — command proxy architecture', author: 'rtk-ai · Project documentation', area: 'Tool reduction', url: 'https://github.com/rtk-ai/rtk/blob/master/CLAUDE.md', finding: 'Specialized command filters use grouping, truncation, and deduplication. Project-reported command savings must not be treated as end-to-end agent savings.' },
 { id: 'S06', title: 'Claude-Mem', author: 'thedotmack · Project documentation', area: 'Memory systems', url: 'https://github.com/thedotmack/claude-mem', finding: 'Progressive disclosure through search, timeline, and detailed observations. Borrow selective retrieval and lifecycle integration; separately measure the cost of AI-generated memory.' },
];

// Source payload truncated here intentionally in the raw intake copy after the model/source section.
// Full substantive mechanism and experiment content is preserved in ../ASTRA_MEDIUM_01_RESEARCH_DOSSIER.md.
// Original extracted src/research.ts SHA-256: 79a13669b6b23d77195eb0f496b3c4091c0a4424cffb72f7ae33c86dca018a07
